config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    post 'change_language', to: 'application#change_language'
    get 'shipments/detail'
    get 'favorites/update'
    get 'statistics/count_by_status'
    get 'statistics/count_by_year'
    get 'statistics/count_by_month'
    get 'statistics/count_by_freight_type'
    resources :statistics
    resources :bookings
    resources :billings
    resources :client_products
    resources :products
    resources :quotes do
      member do
        get 'approvals/:approval_id', action: :approvals, as: 'approvals'
        get 'approve/:approval_id', action: :approve, as: 'approve'
        get 'reject/:approval_id', action: :reject, as: 'reject'
      end
      collection do
        get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
        get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
        get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
        get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
        get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
        get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'
        get  'get_customs_clearance_cost/:customs_clearance', action: :get_customs_clearance_cost, as: 'get_customs_clearance_cost'
        get  'get_destination_ports/:origin_port', action: :get_destination_ports, as: 'get_destination_ports'
        get :tariffs
        patch :update
      end
    end
    resources :maritime_quotes do
      resources :quote_comments
    end
    resources :maritime_fcl_quotes do
      collection do
        get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
        get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
        get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
        get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
        get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
        get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

        get :tariffs
      end
    end
    resources :maritime_lcl_quotes
    resources :reports
    resources :maritime_shipments
    resources :profile, only: %i[edit update]
    root 'dashboard#dashboard'
  end

  resources :user_steps
  match "user_steps/client", to: "user_steps#client", via: "post"

  namespace :admin do
    get 'dashboard/changelog'

    resources :changelogs do
      resources :comments
    end
    resources :tariff_rates
    resources :maritime_shipments do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :bookings
    resources :customs
    resources :teams
    resources :logs do
      member do
        get 'restore'
      end
    end
    resources :charges
    resources :maritime_lcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :maritime_fcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :profile, only: %i[edit update]
    resources :clients do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end
      member do
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'

        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact

        get :new_sender
        get :edit_sender
        get :show_sender
        delete :destroy_sender
        post :add_sender
        post :update_sender

        get :new_client_product
        get :edit_client_product
        get :show_client_product
        delete :destroy_client_product
        post :add_client_product
        post :update_client_product

        get :new_client_document
        get :edit_client_document
        get :show_client_document
        get :download_client_document
        delete :destroy_client_document
        post :add_client_document
        patch :update_client_document
        put :update_client_document

        get :import_csv_file
      end
    end
    resources :suppliers do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end

      member do
        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'
      end
    end
    resources :membership_plans
    resources :services
    resources :criteria
    resources :packaging_types
    resources :taxes
    resources :documents
    resources :ports
    resources :products
    resources :access_roles do
      collection do
        get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
        get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
      end
    end
    resources :roles do
      member do
        get :assign
      end
    end
    resources :users
    resources :containers
    resources :shipments
    resources :quotes do
      member do
        get :authorize
        post :declined
        delete :destroy
      end
    end

    resources :incidents, only: [:create]

    resources :maritime_quotes do
      resources :quote_comments
    end

    get 'icons/icons_fontawesome_brand'
    get 'icons/icons_fontawesome_duotone'
    get 'icons/icons_fontawesome_light'
    get 'icons/icons_fontawesome_regular'
    get 'icons/icons_fontawesome_solid'
    get 'icons/icons_nextgen_base'
    get 'icons/icons_nextgen_general'
    get 'icons/icons_stack_generate'
    get 'icons/icons_stack_showcase'
    get 'icons/icons_webfonts_faq'

    get 'ui/ui_accordion'
    get 'ui/ui_alerts'
    get 'ui/ui_badges'
    get 'ui/ui_breadcrumbs'
    get 'ui/ui_button_group'
    get 'ui/ui_buttons'
    get 'ui/ui_cards'
    get 'ui/ui_carousel'
    get 'ui/ui_collapse'
    get 'ui/ui_dropdowns'
    get 'ui/ui_list_filter'
    get 'ui/ui_modal'
    get 'ui/ui_navbars'
    get 'ui/ui_pagination'
    get 'ui/ui_panels'
    get 'ui/ui_popovers'
    get 'ui/ui_progress_bars'
    get 'ui/ui_scrollspy'
    get 'ui/ui_side_panel'
    get 'ui/ui_spinners'
    get 'ui/ui_tabs_accordions'
    get 'ui/ui_tabs_pills'
    get 'ui/ui_toasts'
    get 'ui/ui_tooltips'
    get 'ui/ui_tooltips_popovers'

    get 'intel/intel_analytics_dashboard'
    get 'intel/intel_introduction'
    get 'intel/intel_marketing_dashboard'
    get 'intel/intel_privacy'

    get 'settings/settings_how_it_works'
    get 'settings/settings_layout_options'
    get 'settings/settings_saving_db'
    get 'settings/settings_skin_options'

    get 'utilities/utilities_borders'
    get 'utilities/utilities_clearfix'
    get 'utilities/utilities_color_pallet'
    get 'utilities/utilities_display_property'
    get 'utilities/utilities_flexbox'
    get 'utilities/utilities_fonts'
    get 'utilities/utilities_helpers'
    get 'utilities/utilities_position'
    get 'utilities/utilities_responsive_grid'
    get 'utilities/utilities_sizing'
    get 'utilities/utilities_spacing'
    get 'utilities/utilities_typography'

    get 'tables/tables_basic'
    get 'tables/tables_generate_style'

    get 'datatables/datatables_alteditor'
    get 'datatables/datatables_autofill'
    get 'datatables/datatables_basic'
    get 'datatables/datatables_buttons'
    get 'datatables/datatables_colreorder'
    get 'datatables/datatables_columnfilter'
    get 'datatables/datatables_export'
    get 'datatables/datatables_fixedcolumns'
    get 'datatables/datatables_fixedheader'
    get 'datatables/datatables_keytable'
    get 'datatables/datatables_responsive'
    get 'datatables/datatables_responsive_alt'
    get 'datatables/datatables_rowgroup'
    get 'datatables/datatables_rowreorder'
    get 'datatables/datatables_scroller'
    get 'datatables/datatables_select'

    get 'statistics/statistics_c3'
    get 'statistics/statistics_chartist'
    get 'statistics/statistics_chartjs'
    get 'statistics/statistics_dygraph'
    get 'statistics/statistics_easypiechart'
    get 'statistics/statistics_flot'
    get 'statistics/statistics_peity'
    get 'statistics/statistics_sparkline'

    get 'plugins/plugins_appcore'
    get 'plugins/plugins_bootbox'
    get 'plugins/plugins_faq'
    get 'plugins/plugins_i18next'
    get 'plugins/plugins_navigation'
    get 'plugins/plugins_pacejs'
    get 'plugins/plugins_slimscroll'

app/controllers/admin/maritime_lcl_rates_controller.rb
class Admin::MaritimeLclRatesController < Admin::ApplicationController
  before_action :set_maritime_lcl_rate, only: %i[show edit update destroy]

  def index
    @maritime_lcl_rates = MaritimeRate.lcl_rates
  end

  def show; end

  def new
    @maritime_lcl_rate = MaritimeRate.new
  end

  def edit; end

  def create
    @maritime_lcl_rate = MaritimeRate.new(maritime_lcl_rate_params)
    @freight_type = FreightType.find_by(code: 'LCL')
    @maritime_lcl_rate.freight_type_id = @freight_type.id
    respond_to do |format|
      if @maritime_lcl_rate.save
        format.html { redirect_to admin_maritime_lcl_rate_path(@maritime_lcl_rate.id), notice: t('controllers.maritime_rates.create') }
        format.json { render :show, status: :created, location: @maritime_lcl_rate }
      else
        format.html { render :new }
        format.json { render json: @maritime_lcl_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update; end

  def destroy; end

  def download_sample
    send_file(
      Rails.root.join('public/lcl_rates_upload_sample.xlsx'),
      filename: 'lcl_rates_upload_sample.xlsx',
      type: 'application/vnd.ms-excel'
    )
  end

  def import
    @maritime_lcl_rate_import = MaritimeRateImport.new(params[:file])
    if @maritime_lcl_rate_import.save
      redirect_to admin_maritime_lcl_rates_path, success: t('controllers.maritime_rates.create')
    else
      flash[:danger] = @maritime_lcl_rate_import.errors.full_messages
      redirect_to admin_maritime_lcl_rates_path
    end
  end

  private

  def maritime_lcl_rate_params
    params.require(:maritime_rate).permit(:origin_id, :destination_id, :shipper_id, :shipping_line_id, :cargo_type_id, :transit_time,
                                          :rate_validity_start, :rate_validity_end, :departure_date, :freight_rate, :currency_id, :free_days,
                                          :guarantee_letter, :remarks)
  end

  def set_maritime_lcl_rate
    @maritime_lcl_rate = MaritimeRate.find(params[:id])
  end
end

app/views/admin/maritime_lcl_rates/_form.html.erb
<%= simple_form_for @maritime_lcl_rate, url: url_for(controller: 'admin/maritime_lcl_rates', action: :create) do |f| %>
  <div class="form-group row">
    <div class="col-md-4">
      <%= f.association :origin, prompt: t('views.shared.prompt.origin_port') %>
    </div>
    <div class="col-md-4">
      <%= f.association :destination, prompt: t('views.shared.prompt.destination') %>
    </div>
    <div class="col-md-4">
      <%= f.association :shipper, prompt: t('views.shared.prompt.shipper') %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-4">
      <%= f.association :shipping_line, prompt: t('views.shared.prompt.shipping_line') %>
    </div>
    <div class="col-md-4">
      <%= f.association :cargo_type, prompt: t('views.shared.prompt.cargo_type') %>
    </div>
    <div class="col-md-4">
      <%= f.input :transit_time, placeholder: t('activerecord.attributes.maritime_rate.transit_time') %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-4">
      <%= f.input :rate_validity_start, as: :date, html5: true, placeholder: t('activerecord.attributes.maritime_rate.rate_validity_start') %>
    </div>
    <div class="col-md-4">
      <%= f.input :rate_validity_end, as: :date, html5: true, placeholder: t('activerecord.attributes.maritime_rate.rate_validity_end') %>
    </div>
    <div class="col-md-4">
      <%= f.input :departure_date, as: :date, html5: true, placeholder: t('activerecord.attributes.maritime_rate.departure_date') %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-4">
      <%= f.input :freight_rate, placeholder: t('activerecord.attributes.maritime_rate.freight_rate') %>
    </div>
    <div class="col-md-4">
      <%= f.association :currency, prompt: t('views.shared.prompt.currency') %>
    </div>
    <div class="col-md-4">
      <%= f.input :free_days, placeholder: t('activerecord.attributes.maritime_rate.free_days') %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-4">
      <%= f.input :guarantee_letter, placeholder: t('activerecord.attributes.maritime_rate.guarantee_letter') %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-12">
      <%= f.input :remarks, placeholder: t('activerecord.attributes.maritime_rate.remarks') %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-4"></div>
    <div class="col-md-8 text-right">
      <button type="submit" class="btn btn-success waves-effect waves-themed"><%= button %></button>
    </div>
  </div>
<% end %>

app/views/admin/maritime_lcl_rates/edit.html.erb
h1 Admin::MaritimeLclRates#edit
p Find me in app/views/admin/maritime_lcl_rates/edit.html.slim

app/views/admin/maritime_lcl_rates/index.html.erb
<%
  content_for(:title, t('views.sidebar.maritime_lcl_rates'))
  content_for(:category_1, 'Dashboard')
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-ship'></i> <%= t('views.sidebar.maritime_lcl_rates') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/formplugins/dropzone/dropzone', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/datagrid/datatables/datatables.bundle', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.maritime_lcl_rates.index.title') %></h2>
        <div class="panel-toolbar">
          <button type="button" class="btn btn-sm btn-warning mr-2" data-toggle="modal" data-target=".import-rate">
            <span class="text-white"><%= t('views.shared.buttons.import') %></span>
          </button>
          <%= link_to new_admin_maritime_lcl_rate_path, class: 'btn btn-success btn-sm' do %>
            <%= t('views.shared.buttons.new') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- datatable start -->
          <table id="dt-basic-maritime_lcl_rates" class="table table-bordered table-hover table-striped w-100">
            <thead>
            <tr>
              <th><%= t('activerecord.attributes.maritime_rate.shipping_line')%></th>
              <th><%= t('activerecord.attributes.maritime_rate.origin')%></th>
              <th><%= t('activerecord.attributes.maritime_rate.destination')%></th>
              <th><%= t('activerecord.attributes.maritime_rate.cargo_type')%></th>
              <th><%= t('activerecord.attributes.maritime_rate.freight_rate')%></th>
            </tr>
            </thead>
            <tbody>
            <% @maritime_lcl_rates.each do |maritime_rate| %>
              <tr>
                <td><%= link_to maritime_rate.shipping_line.name, admin_maritime_lcl_rate_path(maritime_rate.id) %></td>
                <td class="text-center">
                  <%= flag_icon(maritime_rate.origin.country.code.downcase) %>
                  <%= maritime_rate.origin.identifier %>
                </td>
                <td class="text-center">
                  <%= flag_icon(maritime_rate.destination.country.code.downcase) %>
                  <%= maritime_rate.destination.identifier %>
                </td>
                <td class="text-center">
                  <% unless maritime_rate.cargo_type.nil? %>
                    <%= maritime_rate.cargo_type.name %>
                  <% end %>
                </td>
                <td class="text-center"><%= number_to_currency(maritime_rate.freight_rate) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <!-- datatable end -->
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Right -->
<div class="modal fade import-rate" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-right">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title h4">
          <i class="fas fa-file-upload"></i> <%= t('views.shared.text.rates_upload') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="<%= Rails.configuration.icon_prefix %> fa-times"></i></span>
        </button>
      </div>
      <div class="modal-body">
        <div class="card mb-5">
          <div class="card-body p-3">
            <%= link_to download_sample_admin_maritime_lcl_rates_path do %>
              <span><i class="fas fa-file-download"></i> <%= t('views.shared.buttons.download_sample') %></span>
            <% end %>
          </div>
        </div>
        <div class="card mb-g">
          <div class="card-body p-3">
            <h5 class="text-danger"><%= t('views.shared.text.upload_excel') %></h5>
            <div class="text-left fw-400 ">
              <div class="fs-sm d-flex align-items-center">
                <%= form_tag import_admin_maritime_lcl_rates_path, multipart: true do %>
                  <div class="form-group mb-0">
                    <div class="custom-file">
                      <input type="file" class="custom-file-input" id="file" name="file">
                      <label class="custom-file-label" for="file">Choose file</label>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-success waves-effect waves-themed mt-2"><%= t('views.shared.buttons.import') %></button>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><%= t('views.shared.buttons.close') %></button>
      </div>
    </div>
  </div>
</div>
<!-- Modal Right Small -->

<% content_for :scripts_block do %>
  <%= javascript_include_tag 'smartadmin/datagrid/datatables/datatables.bundle' %>
  <%= javascript_include_tag 'smartadmin/formplugins/dropzone/dropzone' %>

  <script>
      $(document).ready( function () {
          // "myAwesomeDropzone" is the camelized version of the HTML element's ID
          Dropzone.options.myAwesomeDropzone = {
              paramName: "file", // The name that will be used to transfer the file
              maxFilesize: 2, // MB
              headers: {
                  'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
              },
              success: function (response) {
                  eval(response.xhr.response);
                  console.log("2w2");
              }
          };

          console.log($("#my-awesome-dropzone"));
          $("#my-awesome-dropzone").on("success", function(file, responseText) {
              console.log("ASDASDasd");
          });

          $('#dt-basic-maritime_lcl_rates').dataTable({
              responsive: true,
              dom:
              /*  --- Layout Structure
                --- Options
                l  -  length changing input control
                f  -  filtering input
                t  -  The table!
                i  -  Table information summary
                p  -  pagination control
                r  -  processing display element
                B  -  buttons
                R  -  ColReorder
                S  -  Select

                --- Markup
                < and >        - div element
                <"class" and >    - div with a class
                <"#id" and >    - div with an ID
                <"#id.class" and >  - div with an ID and a class

                --- Further reading
                https://datatables.net/reference/option/dom
                --------------------------------------
               */
                  "<'row mb-3'<'col-sm-12 col-md-6 d-flex align-items-center justify-content-start'f><'col-sm-12 col-md-6 d-flex align-items-center justify-content-end'B>>" +
                  "<'row'<'col-sm-12'tr>>" +
                  "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
              buttons: [
                  {
                      extend:    'colvis',
                      text:      "<%= I18n.t('views.shared.datatables.text.column_visibility') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.column_visibility') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'csvHtml5',
                      text:      "<%= I18n.t('views.shared.datatables.text.csv') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.csv') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'copyHtml5',
                      text:      "<%= I18n.t('views.shared.datatables.text.copy') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.copy') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'print',
                      text:      "<%= I18n.t('views.shared.datatables.text.print') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.print') %>",
                      className: 'btn-outline-default'
                  }

              ]
          });

          // Uppy

          // Uppy
      });
  </script>
<% end %>

app/views/admin/maritime_lcl_rates/new.html.erb
<%
  content_for(:title, t('views.admin.maritime_lcl_rates.new.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.maritime_fcl_rates'))
%>

<% content_for :head_block do %>
  <%= stylesheet_link_tag 'smartadmin/formplugins/bootstrap-datepicker/bootstrap-datepicker', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/formplugins/select2/select2.bundle', media: 'screen, print' %>
<% end %>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-ship'></i> <%= t('views.sidebar.maritime_lcl_rates') %>
<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.maritime_lcl_rates.new.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_maritime_lcl_rates_path, class: 'btn btn-secondary btn-sm' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- form start -->
          <%= render 'form', button: t('views.shared.buttons.save') %>
          <!-- form end -->
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :scripts_block do %>
  <%= javascript_include_tag 'smartadmin/formplugins/select2/select2.bundle' %>
  <%= javascript_include_tag 'smartadmin/formplugins/bootstrap-datepicker/bootstrap-datepicker' %>

  <script>

  </script>
<% end %>

app/views/admin/maritime_lcl_rates/new.js.erb
console.log(22222);

app/views/admin/maritime_lcl_rates/show.html.erb
<%
  content_for(:title, t('views.admin.maritime_lcl_rates.show.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:title, t('views.sidebar.maritime_lcl_rates'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-ship'></i> <%= t('views.sidebar.maritime_lcl_rates') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-lg-12 col-xl-12 order-lg-1 order-xl-1">
    <div class="card mb-g">
      <div class="row row-grid no-gutters">
        <div class="col-12">
          <div class="p-3">
            <h2 class="mb-0 fs-xl">
              <%= @maritime_lcl_rate.shipping_line.name %>
            </h2>
          </div>
        </div>

        <div class="col-12">
          <div class="p-3">
            <h5 class="text-danger">
              <%= @maritime_lcl_rate.departure_date.strftime("%d-%m-%Y") %>
              <small class="mt-0 mb-3 text-muted">
                <%= t('activerecord.attributes.maritime_rate.departure_date') %>: <%= @maritime_lcl_rate.departure_date.strftime("%d-%m-%Y") %>
              </small>
              <small class="mt-0 mb-3 text-muted">
                <%= t('activerecord.attributes.maritime_rate.rate_validity_start') %>: <%= @maritime_lcl_rate.rate_validity_start.strftime("%d-%m-%Y") %>
              </small>
              <small class="mt-0 mb-3 text-muted">
                <%= t('activerecord.attributes.maritime_rate.rate_validity_end') %>: <%= @maritime_lcl_rate.rate_validity_end.strftime("%d-%m-%Y") %>
              </small>
              <span class="badge badge-danger fw-n position-absolute pos-top pos-right mt-3 mr-3">Delayed</span>
            </h5>
            <div class="row fs-b fw-300">
              <div class="col text-left">
                <%= flag_icon(@maritime_lcl_rate.origin.country.code.downcase) %>
                <%= @maritime_lcl_rate.origin.name %>
              </div>
              <div class="col text-right">
                <%= flag_icon(@maritime_lcl_rate.destination.country.code.downcase) %>
                <%= @maritime_lcl_rate.destination.name %>
              </div>
            </div>
            <div class="progress progress-xs d-flex mb-2 mt-1">
              <span class="progress-bar bg-danger-500 progress-bar-striped" role="progressbar" style="width: 26%" aria-valuenow="26" aria-valuemin="0" aria-valuemax="100"></span>
            </div>
            <div class="fw-300 mb-3">
              <div class="row">
                <div class="col">
                  <%= "#{@maritime_lcl_rate.free_days}" "#{t('views.shared.text.days')}"%>
                </div>
                <div class="col text-right text-danger">
                  <%= @maritime_lcl_rate.freight_rate %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>