config/routes.rb
    root 'dashboard#dashboard'
  end

  resources :user_steps
  match "user_steps/client", to: "user_steps#client", via: "post"

  namespace :admin do
    get 'dashboard/changelog'

    resources :changelogs do
      resources :comments
    end
    resources :tariff_rates
    resources :maritime_shipments do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :bookings
    resources :customs
    resources :teams
    resources :logs do
      member do
        get 'restore'
      end
    end
    resources :charges
    resources :maritime_lcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :maritime_fcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :profile, only: %i[edit update]
    resources :clients do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end
      member do
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'

        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact

        get :new_sender
        get :edit_sender
        get :show_sender
        delete :destroy_sender
        post :add_sender
        post :update_sender

        get :new_client_product
        get :edit_client_product
        get :show_client_product
        delete :destroy_client_product
        post :add_client_product
        post :update_client_product

        get :new_client_document
        get :edit_client_document
        get :show_client_document
        get :download_client_document
        delete :destroy_client_document
        post :add_client_document
        patch :update_client_document
        put :update_client_document

        get :import_csv_file
      end
    end
    resources :suppliers do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end

      member do
        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'
      end
    end
    resources :membership_plans
    resources :services
    resources :criteria
    resources :packaging_types
    resources :taxes
    resources :documents
    resources :ports
    resources :products
    resources :access_roles do
      collection do
        get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
        get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
      end
    end
    resources :roles do
      member do
        get :assign
      end
    end
    resources :users
    resources :containers
    resources :shipments
    resources :quotes do
      member do
        get :authorize
        post :declined
        delete :destroy
      end
    end

    resources :incidents, only: [:create]

    resources :maritime_quotes do
      resources :quote_comments
    end

    get 'icons/icons_fontawesome_brand'
    get 'icons/icons_fontawesome_duotone'
    get 'icons/icons_fontawesome_light'
    get 'icons/icons_fontawesome_regular'
    get 'icons/icons_fontawesome_solid'
    get 'icons/icons_nextgen_base'
    get 'icons/icons_nextgen_general'
    get 'icons/icons_stack_generate'
    get 'icons/icons_stack_showcase'
    get 'icons/icons_webfonts_faq'

    get 'ui/ui_accordion'
    get 'ui/ui_alerts'
    get 'ui/ui_badges'
    get 'ui/ui_breadcrumbs'
    get 'ui/ui_button_group'
    get 'ui/ui_buttons'
    get 'ui/ui_cards'
    get 'ui/ui_carousel'
    get 'ui/ui_collapse'
    get 'ui/ui_dropdowns'
    get 'ui/ui_list_filter'
    get 'ui/ui_modal'
    get 'ui/ui_navbars'
    get 'ui/ui_pagination'
    get 'ui/ui_panels'
    get 'ui/ui_popovers'
    get 'ui/ui_progress_bars'
    get 'ui/ui_scrollspy'
    get 'ui/ui_side_panel'
    get 'ui/ui_spinners'
    get 'ui/ui_tabs_accordions'
    get 'ui/ui_tabs_pills'
    get 'ui/ui_toasts'
    get 'ui/ui_tooltips'
    get 'ui/ui_tooltips_popovers'

    get 'intel/intel_analytics_dashboard'
    get 'intel/intel_introduction'
    get 'intel/intel_marketing_dashboard'
    get 'intel/intel_privacy'

    get 'settings/settings_how_it_works'
    get 'settings/settings_layout_options'
    get 'settings/settings_saving_db'
    get 'settings/settings_skin_options'

    get 'utilities/utilities_borders'
    get 'utilities/utilities_clearfix'
    get 'utilities/utilities_color_pallet'
    get 'utilities/utilities_display_property'
    get 'utilities/utilities_flexbox'
    get 'utilities/utilities_fonts'
    get 'utilities/utilities_helpers'
    get 'utilities/utilities_position'
    get 'utilities/utilities_responsive_grid'
    get 'utilities/utilities_sizing'
    get 'utilities/utilities_spacing'
    get 'utilities/utilities_typography'

    get 'tables/tables_basic'
    get 'tables/tables_generate_style'

    get 'datatables/datatables_alteditor'
    get 'datatables/datatables_autofill'
    get 'datatables/datatables_basic'
    get 'datatables/datatables_buttons'
    get 'datatables/datatables_colreorder'
    get 'datatables/datatables_columnfilter'
    get 'datatables/datatables_export'
    get 'datatables/datatables_fixedcolumns'
    get 'datatables/datatables_fixedheader'
    get 'datatables/datatables_keytable'
    get 'datatables/datatables_responsive'
    get 'datatables/datatables_responsive_alt'
    get 'datatables/datatables_rowgroup'
    get 'datatables/datatables_rowreorder'
    get 'datatables/datatables_scroller'
    get 'datatables/datatables_select'

    get 'statistics/statistics_c3'
    get 'statistics/statistics_chartist'
    get 'statistics/statistics_chartjs'
    get 'statistics/statistics_dygraph'
    get 'statistics/statistics_easypiechart'
    get 'statistics/statistics_flot'
    get 'statistics/statistics_peity'
    get 'statistics/statistics_sparkline'

    get 'plugins/plugins_appcore'
    get 'plugins/plugins_bootbox'
    get 'plugins/plugins_faq'
    get 'plugins/plugins_i18next'
    get 'plugins/plugins_navigation'
    get 'plugins/plugins_pacejs'
    get 'plugins/plugins_slimscroll'
    get 'plugins/plugins_smartpanels'
    get 'plugins/plugins_throttle'
    get 'plugins/plugins_waves'

    get 'page/page_chat'
    get 'page/page_confirmation'
    get 'page/page_contacts'
    get 'page/page_error'
    get 'page/page_error_404'
    get 'page/page_error_announced'
    get 'page/page_forget'
    get 'page/page_forum_discussion'
    get 'page/page_forum_list'
    get 'page/page_forum_threads'
    get 'page/page_inbox_general'
    get 'page/page_inbox_read'
    get 'page/page_inbox_write'
    get 'page/page_invoice'
    get 'page/page_locked'
    get 'page/page_login'
    get 'page/page_login_alt'
    get 'page/page_profile'
    get 'page/page_projects'
    get 'page/page_register'
    get 'page/page_search'

    get 'form/form_basic_inputs'
    get 'form/form_checkbox_radio'
    get 'form/form_input_groups'
    get 'form/form_validation'

    get 'form_plugins/form_plugins_colorpicker'
    get 'form_plugins/form_plugins_datepicker'
    get 'form_plugins/form_plugins_daterange_picker'
    get 'form_plugins/form_plugins_dropzone'
    get 'form_plugins/form_plugins_imagecropper'
    get 'form_plugins/form_plugins_inputmask'
    get 'form_plugins/form_plugins_ionrangeslider'
    get 'form_plugins/form_plugins_markdown'
    get 'form_plugins/form_plugins_nouislider'
    get 'form_plugins/form_plugins_select2'
    get 'form_plugins/form_plugins_summernote'
    get 'form_plugins/form_plugins_wizard'

    get 'miscellaneous/miscellaneous_fullcalendar'
    get 'miscellaneous/miscellaneous_lightgallery'
    get 'miscellaneous/miscellaneous_treeview'
    get 'notifications/notifications_sweetalert2'
    get 'notifications/notifications_toastr'

    post 'change_language', to: 'application#change_language'
    root to: 'dashboard#index'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :quote_contact_emails, only: [:create]
  post 'welcome/contact_us'
  post 'welcome/request_quote'
  post 'welcome/quote'
  get 'welcome/get_destination_ports/:origin_id', to: 'welcome#get_destination_ports', as: 'welcome_get_destination_ports'

  get 'intel/intel_analytics_dashboard'
  get 'intel/intel_introduction'
  get 'intel/intel_marketing_dashboard'
  get 'intel/intel_privacy'

  post 'requests/quote'
  get 'welcome/blank'

  resources :maritime_quotes do
    collection do
      get 'optional_service/:optional_service_id', action: :optional_service, as: 'optional_service'
    end
  end

  resources :welcome do
    collection do
      get 'optional_services/:rate_id', action: :optional_services, as: 'optional_services'
      get :search_rates
      get :preview_quote

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :bigint           not null, primary key
#  code       :string
#  deleted_at :datetime
#  name       :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_roles_on_deleted_at  (deleted_at)
#  index_roles_on_slug        (slug) UNIQUE
#
class Role < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :users, inverse_of: :role, dependent: :destroy
  has_many :access_roles, inverse_of: :role, dependent: :destroy
  has_many :accesses, through: :access_roles, inverse_of: :roles

  accepts_nested_attributes_for :access_roles

  validates :name, presence: true
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::ApplicationController
  before_action :set_role, only: %i[edit show update destroy assign]
  before_action :set_accesses, only: %i[show assign]

  def index
    @roles = Role.all.order(:name)
  end

  def show; end

  def new
    @role = Role.new
  end

  def edit; end

  def create
    @role = Role.new(role_params)
    if @role.save
      flash[:success] = t('controllers.roles.create')
      redirect_to admin_roles_path
    else
      render :new
    end
  end

  def update
    if @role.update(role_params)
      redirect_to admin_role_path(@role.id)
      flash[:success] = t('controllers.roles.update')
    else
      render :new
    end
  end

  def destroy
    if @role.destroy
      flash[:danger] = t('controllers.user.destroy')
      redirect_to admin_roles_path
    else
      render :show
    end
  end

  def assign; end

  private

  def role_params
    params.require(:role).permit(:name)
  end

  def set_role
    @role = Role.friendly.find(params[:id])
  end

  def set_accesses
    @access = AccessRole.where(role_id: @role.id)
  end
end

app/views/admin/roles/_form.html.erb
<%= simple_form_for [:admin, @role] do |f| %>
  <div class="form-group row">
    <div class="col-md-6">
      <%= f.input :name, placeholder: t('activerecord.attributes.role.name') %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-4"></div>
    <div class="col-md-8 text-right">
      <button type="submit" class="btn btn-success waves-effect waves-themed"><%= button %></button>
    </div>
  </div>
<% end %>

app/views/admin/roles/assign.html.erb
<%
  content_for(:title, t('views.admin.roles.assign.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.roles'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-lock'></i>  <%= t('views.sidebar.roles') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-duotone', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>

  <%= stylesheet_link_tag 'smartadmin/notifications/toastr/toastr', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-lg-12 col-xl-6">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.roles.assign.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_role_path(@role.id), class: 'btn btn-primary btn-sm' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <h3 class="frame-heading"><%= @role.name %></h3>
          <div class="frame-wrap p-0 border-0 m-0">
            <table class="table m-0 table-bordered">
              <thead>
                <tr>
                  <th>
                    <%= "#{t('activerecord.models.system_module.other')}/#{t('activerecord.models.access.other')}" %>
                  </th>
                  <% prepare_hash %>
                  <% @access_order = Access.all.order("id ASC") %>
                  <% @access_order.each do |access| %>
                    <th class="text-center">
                      <%= t("views.admin.access.#{access.name.downcase}") %>
                    </th>
                  <% end %>
                </tr>
              </thead>

              <tbody>
                <% access = @access_order.all.pluck(:id) %>
                <% SystemModule.all.each do |sm| %>
                  <tr>
                    <input type="hidden" name="role_id" class= 'role_id' value= <%= @role.id %> >
                    <th>
                      <%= t("activerecord.models.#{squish(sm.name)}.other") %>
                    </th>
                    <td class="text-center">
                      <label class="checkbox checkbox-inline">
                        <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[0])) %>  value= '<%= access[0] %> : <%= sm.id  %>' >
                        <span></span>
                      </label>
                    </td>
                    <td class="text-center">
                      <label class="checkbox checkbox-inline">
                        <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[1])) %>  value= '<%= access[1] %> : <%= sm.id  %>' >
                        <span></span>
                      </label>
                    </td>
                    <td class="text-center">
                      <label class="checkbox checkbox-inline">
                        <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[2])) %>  value= '<%= access[2] %> : <%= sm.id  %>' >
                        <span></span>
                      </label>
                    </td>
                    <td class="text-center">
                      <label class="checkbox checkbox-inline">
                        <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[3])) %>  value= '<%= access[3] %> : <%= sm.id  %>' >
                        <span></span>
                      </label>
                    </td>
                    <td class="text-center">
                      <label class="checkbox checkbox-inline">
                        <input type="checkbox"  <%= 'checked' if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[4])) %>  value= '<%= access[4] %> : <%= sm.id  %>' >
                        <span></span>
                      </label>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :scripts_block do %>
  <%= javascript_include_tag 'smartadmin/notifications/toastr/toastr' %>

  <script>

      $(document).ready(function () {

          $(':checkbox').on('change', function() {
              var $this = $(this);
              var ids = $this.val();
              var id_array = ids.split(':');
              var system_module_id = id_array[1];
              var access_id = id_array[0];
              var role_id = $('.role_id').val();
              var url;
              console.log(system_module_id.trim());
              console.log(access_id.trim());
              console.log(role_id.trim());

              if (this.checked) {
                  url = "/admin/access_roles/add_access/" + role_id.trim() + "/" + access_id.trim() + "/" + system_module_id.trim();
              } else {
                  url = "/admin/access_roles/remove_access/" + role_id.trim() + "/" + access_id.trim() + "/" + system_module_id.trim();
              }
              console.log(url);
              $.ajax({
                  url: url,
                  type: "get",
                  success: function (data) {
                      if (data.type == 'success') {
                          toastr.success(data.response)
                      } else {
                          toastr.error(data.response)
                      }
                  },
                  error: function (data) {
                      console.log(data);
                  }
              })
          });
      });
  </script>
<% end %>

app/views/admin/roles/edit.html.erb
<%
  content_for(:title, t('views.admin.roles.edit.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.roles'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-lock'></i> <%= t('views.sidebar.roles') %>
<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.roles.edit.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_role_path(@role.id), class: 'btn btn-secondary btn-sm' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- form start -->
          <%= render 'form', button: t('views.shared.buttons.update') %>
          <!-- form end -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/roles/index.html.erb
<%
  content_for(:title, t('views.sidebar.roles'))
  content_for(:category_1, 'Dashboard')
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-lock'></i> <%= t('views.sidebar.roles') %>
<% end %>

<% content_for :head_block do %>
  <%= stylesheet_link_tag 'smartadmin/datagrid/datatables/datatables.bundle', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.roles.index.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to new_admin_role_path, class: 'btn btn-success btn-sm' do %>
            <%= t('views.shared.buttons.new') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- datatable start -->
          <table id="dt-basic-roles" class="table table-bordered table-hover table-striped w-100">
            <thead>
              <tr>
                <th><%= t('activerecord.attributes.role.id') %></th>
                <th><%= t('activerecord.attributes.role.name') %></th>
              </tr>
            </thead>
            <tbody>
            <% @roles.each do |role| %>
              <tr>
                <td><%= role.id %></td>
                <td><%= link_to role.name, admin_role_path(role.id) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <!-- datatable end -->
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :scripts_block do %>
  <!-- datatble responsive bundle contains:
    + jquery.dataTables.js
    + dataTables.bootstrap4.js
    + dataTables.autofill.js
    + dataTables.buttons.js
    + buttons.bootstrap4.js
    + buttons.html5.js
    + buttons.print.js
    + buttons.colVis.js
    + dataTables.colreorder.js
    + dataTables.fixedcolumns.js
    + dataTables.fixedheader.js
    + dataTables.keytable.js
    + dataTables.responsive.js
    + dataTables.rowgroup.js
    + dataTables.rowreorder.js
    + dataTables.scroller.js
    + dataTables.select.js
    + datatables.styles.app.js
    + datatables.styles.buttons.app.js -->
  <%= javascript_include_tag 'smartadmin/datagrid/datatables/datatables.bundle' %>
  <script>
      $(document).ready( function () {
          $('#dt-basic-roles').dataTable({
              responsive: true,
              dom:
              /*  --- Layout Structure
                --- Options
                l  -  length changing input control
                f  -  filtering input
                t  -  The table!
                i  -  Table information summary
                p  -  pagination control
                r  -  processing display element
                B  -  buttons
                R  -  ColReorder
                S  -  Select

                --- Markup
                < and >        - div element
                <"class" and >    - div with a class
                <"#id" and >    - div with an ID
                <"#id.class" and >  - div with an ID and a class

                --- Further reading
                https://datatables.net/reference/option/dom
                --------------------------------------
               */
                  "<'row mb-3'<'col-sm-12 col-md-6 d-flex align-items-center justify-content-start'f><'col-sm-12 col-md-6 d-flex align-items-center justify-content-end'B>>" +
                  "<'row'<'col-sm-12'tr>>" +
                  "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
              buttons: [
                  {
                      extend:    'colvis',
                      text:      "<%= I18n.t('views.shared.datatables.text.column_visibility') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.column_visibility') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'csvHtml5',
                      text:      "<%= I18n.t('views.shared.datatables.text.csv') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.csv') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'copyHtml5',
                      text:      "<%= I18n.t('views.shared.datatables.text.copy') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.copy') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'print',
                      text:      "<%= I18n.t('views.shared.datatables.text.print') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.print') %>",
                      className: 'btn-outline-default'
                  }

              ]
          });
      });
  </script>
<% end %>

app/views/admin/roles/new.html.erb
<%
  content_for(:title, t('views.admin.roles.new.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.roles'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-lock'></i> <%= t('views.sidebar.roles') %>
<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.roles.new.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_roles_path, class: 'btn btn-secondary btn-sm' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- form start -->
          <%= render 'form', button: t('views.shared.buttons.save') %>
          <!-- form end -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/roles/show.html.erb
<%
  content_for(:title, t('views.admin.roles.show.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.roles'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fal fa-lock'></i>  <%= t('views.sidebar.roles') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-duotone', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-lg-12 col-xl-6">
    <!--Basic tables-->
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.roles.show.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_roles_path, class: 'btn btn-secondary btn-sm ml-2' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
          <%= link_to({ action: :destroy, id: @role.id }, class: "btn btn-primary btn-sm ml-2", method: :delete, data: { confirm: t('views.shared.text.are_you_ok?') }) do %>
            <%= t('views.shared.buttons.destroy') %>
          <% end %>
          <%= link_to assign_admin_role_path(@role.id), class: 'btn btn-warning btn-sm ml-2 text-white' do %>
            <%= t('views.shared.buttons.assign') %>
          <% end %>
          <%= link_to edit_admin_role_path(@role.id), class: 'btn btn-info btn-sm ml-2' do %>
            <%= t('views.shared.buttons.edit') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <h3 class="frame-heading"><%= @role.name %></h3>
          <div class="frame-wrap p-0 border-0 m-0">
            <table class="table m-0 table-bordered">
              <thead>
                <tr>
                  <th>
                    <%= "#{t('activerecord.models.system_module.other')}/#{t('activerecord.models.access.other')}" %>
                  </th>
                  <% prepare_hash %>
                  <% @access_order = Access.all.order("id ASC") %>
                  <% @access_order.each do |access| %>
                    <th class="text-center">
                      <%= t("views.admin.access.#{access.name.downcase}") %>
                    </th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% access = @access_order.all.pluck(:id) %>
                <% SystemModule.all.each do |sm| %>
                  <tr>
                    <th>
                      <%= t("activerecord.models.#{squish(sm.name)}.other") %>
                    </th>
                    <td class="text-center">
                      <%  if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[0])) %>
                        <i class="fas fa-check" style="color: green"></i>
                      <%  else %>
                        <i class="fas fa-times" style="color: red"></i>
                      <%  end %>
                    </td>
                    <td class="text-center">
                      <%  if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[1])) %>
                        <i class="fas fa-check" style="color: green"></i>
                      <%  else %>
                        <i class="fas fa-times" style="color: red"></i>
                      <%  end %>
                    </td>
                    <td class="text-center">
                      <%  if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[2])) %>
                        <i class="fas fa-check" style="color: green"></i>
                      <%  else %>
                        <i class="fas fa-times" style="color: red"></i>
                      <%  end %>
                    </td>
                    <td class="text-center">
                      <%  if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[3])) %>
                        <i class="fas fa-check" style="color: green"></i>
                      <%  else %>
                        <i class="fas fa-times" style="color: red"></i>
                      <%  end %>
                    </td>
                    <td class="text-center">
                      <%  if (@permissions[sm.id].present? && @permissions[sm.id].include?(access[4])) %>
                        <i class="fas fa-check" style="color: green"></i>
                      <%  else %>
                        <i class="fas fa-times" style="color: red"></i>
                      <%  end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>