config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    post 'change_language', to: 'application#change_language'
    get 'shipments/detail'
    get 'favorites/update'
    get 'statistics/count_by_status'
    get 'statistics/count_by_year'
    get 'statistics/count_by_month'
    get 'statistics/count_by_freight_type'
    resources :statistics
    resources :bookings
    resources :billings
    resources :client_products
    resources :products
    resources :quotes do
      member do
        get 'approvals/:approval_id', action: :approvals, as: 'approvals'
        get 'approve/:approval_id', action: :approve, as: 'approve'
        get 'reject/:approval_id', action: :reject, as: 'reject'
      end
      collection do
        get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
        get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
        get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
        get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
        get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
        get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'
        get  'get_customs_clearance_cost/:customs_clearance', action: :get_customs_clearance_cost, as: 'get_customs_clearance_cost'
        get  'get_destination_ports/:origin_port', action: :get_destination_ports, as: 'get_destination_ports'
        get :tariffs
        patch :update
      end
    end
    resources :maritime_quotes do
      resources :quote_comments
    end
    resources :maritime_fcl_quotes do
      collection do
        get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
        get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
        get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
        get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
        get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
        get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

        get :tariffs
      end
    end
    resources :maritime_lcl_quotes
    resources :reports
    resources :maritime_shipments
    resources :profile, only: %i[edit update]
    root 'dashboard#dashboard'
  end

  resources :user_steps
  match "user_steps/client", to: "user_steps#client", via: "post"

  namespace :admin do
    get 'dashboard/changelog'

    resources :changelogs do
      resources :comments
    end
    resources :tariff_rates
    resources :maritime_shipments do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :bookings
    resources :customs
    resources :teams
    resources :logs do
      member do
        get 'restore'
      end
    end
    resources :charges
    resources :maritime_lcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :maritime_fcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :profile, only: %i[edit update]
    resources :clients do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end
      member do
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'

        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact

        get :new_sender
        get :edit_sender
        get :show_sender
        delete :destroy_sender
        post :add_sender
        post :update_sender

        get :new_client_product
        get :edit_client_product
        get :show_client_product
        delete :destroy_client_product
        post :add_client_product
        post :update_client_product

        get :new_client_document
        get :edit_client_document
        get :show_client_document
        get :download_client_document
        delete :destroy_client_document
        post :add_client_document
        patch :update_client_document
        put :update_client_document

        get :import_csv_file
      end
    end
    resources :suppliers do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end

      member do
        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'
      end
    end
    resources :membership_plans
    resources :services
    resources :criteria
    resources :packaging_types
    resources :taxes
    resources :documents
    resources :ports
    resources :products
    resources :access_roles do
      collection do
        get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
        get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
      end
    end
    resources :roles do
      member do
        get :assign
      end
    end
    resources :users
    resources :containers
    resources :shipments
    resources :quotes do
      member do
        get :authorize
        post :declined
        delete :destroy
      end
    end

    resources :incidents, only: [:create]

    resources :maritime_quotes do
      resources :quote_comments
    end

    get 'icons/icons_fontawesome_brand'
    get 'icons/icons_fontawesome_duotone'
    get 'icons/icons_fontawesome_light'
    get 'icons/icons_fontawesome_regular'
    get 'icons/icons_fontawesome_solid'
    get 'icons/icons_nextgen_base'
    get 'icons/icons_nextgen_general'
    get 'icons/icons_stack_generate'
    get 'icons/icons_stack_showcase'
    get 'icons/icons_webfonts_faq'

    get 'ui/ui_accordion'
    get 'ui/ui_alerts'
    get 'ui/ui_badges'
    get 'ui/ui_breadcrumbs'
    get 'ui/ui_button_group'
    get 'ui/ui_buttons'
    get 'ui/ui_cards'
    get 'ui/ui_carousel'
    get 'ui/ui_collapse'
    get 'ui/ui_dropdowns'
    get 'ui/ui_list_filter'
    get 'ui/ui_modal'
    get 'ui/ui_navbars'
    get 'ui/ui_pagination'
    get 'ui/ui_panels'
    get 'ui/ui_popovers'
    get 'ui/ui_progress_bars'
    get 'ui/ui_scrollspy'
    get 'ui/ui_side_panel'
    get 'ui/ui_spinners'
    get 'ui/ui_tabs_accordions'
    get 'ui/ui_tabs_pills'
    get 'ui/ui_toasts'
    get 'ui/ui_tooltips'
    get 'ui/ui_tooltips_popovers'

    get 'intel/intel_analytics_dashboard'
    get 'intel/intel_introduction'
    get 'intel/intel_marketing_dashboard'
    get 'intel/intel_privacy'

    get 'settings/settings_how_it_works'
    get 'settings/settings_layout_options'
    get 'settings/settings_saving_db'
    get 'settings/settings_skin_options'

    get 'utilities/utilities_borders'
    get 'utilities/utilities_clearfix'
    get 'utilities/utilities_color_pallet'
    get 'utilities/utilities_display_property'
    get 'utilities/utilities_flexbox'
    get 'utilities/utilities_fonts'
    get 'utilities/utilities_helpers'
    get 'utilities/utilities_position'
    get 'utilities/utilities_responsive_grid'
    get 'utilities/utilities_sizing'
    get 'utilities/utilities_spacing'
    get 'utilities/utilities_typography'

    get 'tables/tables_basic'
    get 'tables/tables_generate_style'

    get 'datatables/datatables_alteditor'
    get 'datatables/datatables_autofill'
    get 'datatables/datatables_basic'
    get 'datatables/datatables_buttons'
    get 'datatables/datatables_colreorder'
    get 'datatables/datatables_columnfilter'
    get 'datatables/datatables_export'
    get 'datatables/datatables_fixedcolumns'
    get 'datatables/datatables_fixedheader'
    get 'datatables/datatables_keytable'
    get 'datatables/datatables_responsive'
    get 'datatables/datatables_responsive_alt'
    get 'datatables/datatables_rowgroup'
    get 'datatables/datatables_rowreorder'
    get 'datatables/datatables_scroller'
    get 'datatables/datatables_select'

    get 'statistics/statistics_c3'
    get 'statistics/statistics_chartist'
    get 'statistics/statistics_chartjs'
    get 'statistics/statistics_dygraph'
    get 'statistics/statistics_easypiechart'
    get 'statistics/statistics_flot'
    get 'statistics/statistics_peity'
    get 'statistics/statistics_sparkline'

    get 'plugins/plugins_appcore'
    get 'plugins/plugins_bootbox'
    get 'plugins/plugins_faq'
    get 'plugins/plugins_i18next'
    get 'plugins/plugins_navigation'
    get 'plugins/plugins_pacejs'
    get 'plugins/plugins_slimscroll'

app/models/custom.rb
# == Schema Information
#
# Table name: customs
#
#  id              :bigint           not null, primary key
#  active?         :boolean
#  code            :string
#  custom          :string
#  deleted_at      :datetime
#  fcl_expo_rate   :decimal(, )
#  fcl_impo_rate   :decimal(, )
#  lcl_expo_rate   :decimal(, )
#  lcl_impo_rate   :decimal(, )
#  rate            :decimal(, )
#  section         :string
#  slug            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  service_mode_id :bigint
#
# Indexes
#
#  index_customs_on_deleted_at       (deleted_at)
#  index_customs_on_service_mode_id  (service_mode_id)
#  index_customs_on_slug             (slug) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (service_mode_id => service_modes.id)
#
class Custom < ApplicationRecord
  belongs_to :service_mode, inverse_of: :customs

  validates :custom, :code, presence: true
end

app/controllers/admin/customs_controller.rb
class Admin::CustomsController < Admin::ApplicationController
  before_action :set_custom, only: %i[show edit update destroy]

  def index
    @customs = Custom.where(active?: true)
  end

  def show; end

  def new
    @custom = Custom.new
  end

  def edit; end

  def create
    @custom = Custom.new(custom_params)
    if @custom.save
      redirect_to admin_customs_path
      flash[:success] = t('controllers.customs.create')
    else
      render :new
    end
  end

  def update
    if @custom.update(custom_params)
      redirect_to admin_customs_path
      flash[:success] = t('controllers.customs.update')
    else
      render :edit
    end
  end

  def destroy
    if @custom.destroy
      flash[:danger] = t('controllers.customs.destroy')
      redirect_to admin_customs_path
    else
      render :show
    end
  end

  private

  def custom_params
    params.require(:custom).permit(:code, :custom, :rate, :fcl_expo_rate, :fcl_impo_rate, :lcl_expo_rate, :lcl_impo_rate, :active?, :service_mode_id)
  end

  def set_custom
    @custom = Custom.find(params[:id])
  end
end

app/views/admin/customs/_form.html.erb
<%= simple_form_for [:admin, @custom] do |f| %>
  <div class="form-group row">
    <div class="col-md-6">
      <%= f.input :code, placeholder: t('activerecord.attributes.custom.code') %>
    </div>
    <div class="col-md-6">
      <%= f.input :custom, placeholder: t('activerecord.attributes.custom.custom') %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= f.association :service_mode, placeholder: t('activerecord.attributes.custom.service_mode'), prompt: t('views.shared.prompt.service_mode') %>
    </div>
    <div class="col-md-6" id="rate">
      <%= f.input :rate, placeholder: t('activerecord.attributes.custom.rate') %>
    </div>
  </div>

  <div class="form-group row hide-element" id="fcl">
    <div class="col-md-6 " id="fcl_expo_rate">
      <%= f.input :fcl_expo_rate, placeholder: t('activerecord.attributes.custom.fcl_expo_rate') %>
    </div>
    <div class="col-md-6 " id="fcl_impo_rate">
      <%= f.input :fcl_impo_rate, placeholder: t('activerecord.attributes.custom.fcl_impo_rate') %>
    </div>
  </div>
  <div class="form-group row hide-element" id="lcl">
    <div class="col-md-6 " id="lcl_expo_rate">
      <%= f.input :lcl_expo_rate, placeholder: t('activerecord.attributes.custom.lcl_expo_rate') %>
    </div>
    <div class="col-md-6 " id="lcl_impo_rate">
      <%= f.input :lcl_impo_rate, placeholder: t('activerecord.attributes.custom.lcl_impo_rate') %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= f.input :active? %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-4"></div>
    <div class="col-md-8 text-right">
      <button type="submit" class="btn btn-success waves-effect waves-themed"><%= button %></button>
    </div>
  </div>
<% end %>

<% content_for :scripts_block do %>
  <script>
      console.log("dsfdscf")
      $(document).ready(function () {
          console.log("Data:")
          service_mode = $("#custom_service_mode_id option:selected").text();
          console.log(service_mode);
          if (service_mode == 'Servicios Marítimos') {
              $("#fcl").removeClass('hide-element');
              $("#lcl").removeClass('hide-element');
              $("#rate").addClass('hide-element');
          } else {
              $("#fcl").addClass('hide-element');
              $("#lcl").addClass('hide-element');
              $("#rate").removeClass('hide-element');
          }

          console.log($("#custom_service_mode_id"));
          $("#custom_service_mode_id").change(function () {
              service_mode = $("#custom_service_mode_id option:selected").text();
              console.log(service_mode);
              if (service_mode == 'Servicios Marítimos') {
                  $("#fcl").removeClass('hide-element');
                  $("#lcl").removeClass('hide-element');
                  $("#rate").addClass('hide-element');
              } else {
                  $("#custom_fcl_expo_rate").val('');
                  $("#custom_fcl_impo_rate").val('');
                  $("#custom_lcl_expo_rate").val('');
                  $("#custom_lcl_impo_rate").val('');
                  $("#fcl").addClass('hide-element');
                  $("#lcl").addClass('hide-element');
                  $("#rate").removeClass('hide-element');
              }
          })
      });
  </script>
<% end %>

app/views/admin/customs/edit.html.erb
<%
  content_for(:title, t('views.admin.customs.edit.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.customs'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fab fa-intercom'></i> <%= t('views.sidebar.customs') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>

<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.customs.edit.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_custom_path(@custom.id), class: 'btn btn-secondary btn-sm' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- form start -->
          <%= render 'form', button: t('views.shared.buttons.update') %>
          <!-- form end -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customs/index.html.erb
<%
  content_for(:title, t('views.sidebar.customs'))
  content_for(:category_1, 'Dashboard')
%>

<% content_for :heading do %>
  <i class='subheader-icon fab fa-intercom'></i> <%= t('views.sidebar.customs') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>

  <%= stylesheet_link_tag 'smartadmin/datagrid/datatables/datatables.bundle', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.customs.index.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to new_admin_custom_path, class: 'btn btn-success btn-sm' do %>
            <%= t('views.shared.buttons.new') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- datatable start -->
          <table id="dt-basic-customs" class="table table-bordered table-hover table-striped w-100">
            <thead>
              <tr>
                <th><%= t('activerecord.attributes.custom.id')%></th>
                <th><%= t('activerecord.attributes.custom.code')%></th>
                <th><%= t('activerecord.attributes.custom.custom')%></th>
              </tr>
            </thead>
            <tbody>
              <% @customs.each do |custom| %>
                <tr>
                  <td><%= link_to custom.id, admin_custom_path(custom.id) %></td>
                  <td><%= custom.code %></td>
                  <td><%= custom.custom %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <!-- datatable end -->
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :scripts_block do %>
  <!-- datatble responsive bundle contains:
    + jquery.dataTables.js
    + dataTables.bootstrap4.js
    + dataTables.autofill.js
    + dataTables.buttons.js
    + buttons.bootstrap4.js
    + buttons.html5.js
    + buttons.print.js
    + buttons.colVis.js
    + dataTables.colreorder.js
    + dataTables.fixedcolumns.js
    + dataTables.fixedheader.js
    + dataTables.keytable.js
    + dataTables.responsive.js
    + dataTables.rowgroup.js
    + dataTables.rowreorder.js
    + dataTables.scroller.js
    + dataTables.select.js
    + datatables.styles.app.js
    + datatables.styles.buttons.app.js -->
  <%= javascript_include_tag 'smartadmin/datagrid/datatables/datatables.bundle' %>
  <script>
      $(document).ready( function () {
          $('#dt-basic-customs').dataTable({
              responsive: true,
              dom:
              /*  --- Layout Structure
                --- Options
                l  -  length changing input control
                f  -  filtering input
                t  -  The table!
                i  -  Table information summary
                p  -  pagination control
                r  -  processing display element
                B  -  buttons
                R  -  ColReorder
                S  -  Select

                --- Markup
                < and >        - div element
                <"class" and >    - div with a class
                <"#id" and >    - div with an ID
                <"#id.class" and >  - div with an ID and a class

                --- Further reading
                https://datatables.net/reference/option/dom
                --------------------------------------
               */
                  "<'row mb-3'<'col-sm-12 col-md-6 d-flex align-items-center justify-content-start'f><'col-sm-12 col-md-6 d-flex align-items-center justify-content-end'B>>" +
                  "<'row'<'col-sm-12'tr>>" +
                  "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
              buttons: [
                  {
                      extend:    'colvis',
                      text:      "<%= I18n.t('views.shared.datatables.text.column_visibility') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.column_visibility') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'csvHtml5',
                      text:      "<%= I18n.t('views.shared.datatables.text.csv') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.csv') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'copyHtml5',
                      text:      "<%= I18n.t('views.shared.datatables.text.copy') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.copy') %>",
                      className: 'btn-outline-default'
                  },
                  {
                      extend:    'print',
                      text:      "<%= I18n.t('views.shared.datatables.text.print') %>",
                      titleAttr: "<%= I18n.t('views.shared.datatables.titleAttr.print') %>",
                      className: 'btn-outline-default'
                  }

              ]
          });
      });
  </script>
<% end %>

app/views/admin/customs/new.html.erb
<%
  content_for(:title, t('views.admin.customs.new.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.customs'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fab fa-intercom'></i> <%= t('views.sidebar.customs') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>

<% end %>

<div class="row">
  <div class="col-xl-12">
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.customs.new.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_customs_path, class: 'btn btn-secondary btn-sm' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <!-- form start -->
          <%= render 'form', button: t('views.shared.buttons.save') %>
          <!-- form end -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customs/show.html.erb
<%
  content_for(:title, t('views.admin.customs.show.title'))
  content_for(:category_1, 'Dashboard')
  content_for(:category_2, t('views.sidebar.customs'))
%>

<% content_for :heading do %>
  <i class='subheader-icon fab fa-intercom'></i> <%= t('views.sidebar.customs') %>
<% end %>

<% content_for :head_block do %>
  <!-- Optional: page related CSS-->
  <%= stylesheet_link_tag 'smartadmin/fa-brands', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-duotone', media: 'screen, print' %>
  <%= stylesheet_link_tag 'smartadmin/fa-solid', media: 'screen, print' %>
<% end %>

<div class="row">
  <div class="col-lg-12 col-xl-12">
    <!--Basic tables-->
    <div id="panel-1" class="panel">
      <div class="panel-hdr">
        <h2><%= t('views.admin.customs.show.title') %></h2>
        <div class="panel-toolbar">
          <%= link_to admin_customs_path, class: 'btn btn-secondary btn-sm ml-2' do %>
            <%= t('views.shared.buttons.back') %>
          <% end %>
          <%= link_to({ action: :destroy, id: @custom.id }, class: "btn btn-primary btn-sm ml-2", method: :delete, data: { confirm: t('views.shared.text.are_you_ok?') }) do %>
            <%= t('views.shared.buttons.destroy') %>
          <% end %>
          <%= link_to edit_admin_custom_path(@custom.id), class: 'btn btn-info btn-sm ml-2' do %>
            <%= t('views.shared.buttons.edit') %>
          <% end %>
        </div>
      </div>
      <div class="panel-container show">
        <div class="panel-content">
          <div class="frame-wrap p-0 border-0 m-0">
            <div class="form-group row my-2">
              <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.id') %>:</span>
              <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= @custom.id %></span>

              <label class="col-2 col-form-label"><%= t('activerecord.attributes.custom.code') %>:</label>
              <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= @custom.code %></span>
            </div>

            <div class="form-group row my-2">
              <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.custom') %>:</span>
              <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= @custom.custom  %></span>
              <% if @custom.service_mode.name !=  "Servicios Marítimos" %>
                <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.rate') %>:</span>
                <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= number_to_currency @custom.rate  %></span>
              <% end %>
            </div>
            <% if @custom.service_mode.name ==  "Servicios Marítimos" %>
              <div class="form-group row my-2">
                <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.fcl_expo_rate') %>:</span>
                <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= number_to_currency @custom.fcl_expo_rate  %></span>
                <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.fcl_impo_rate') %>:</span>
                <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= number_to_currency @custom.fcl_impo_rate %></span>
              </div>
              <div class="form-group row my-2">
                <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.lcl_expo_rate') %>:</span>
                <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= number_to_currency @custom.lcl_expo_rate  %></span>
                <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.lcl_impo_rate') %>:</span>
                <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= number_to_currency @custom.lcl_impo_rate %></span>
              </div>
            <% end %>
            <div class="form-group row my-2">
              <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.created_at') %>:</span>
              <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= @custom.created_at %>°</span>


              <span class="col-2 col-form-label"><%= t('activerecord.attributes.custom.updated_at') %>:</span>
              <span class="col-4 col-form-label control-plaintext font-weight-bolder"><%= @custom.updated_at %>°</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>