config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    post 'change_language', to: 'application#change_language'
    get 'shipments/detail'
    get 'favorites/update'
    get 'statistics/count_by_status'
    get 'statistics/count_by_year'
    get 'statistics/count_by_month'
    get 'statistics/count_by_freight_type'
    resources :statistics
    resources :bookings
    resources :billings
    resources :client_products
    resources :products
    resources :quotes do
      member do
        get 'approvals/:approval_id', action: :approvals, as: 'approvals'
        get 'approve/:approval_id', action: :approve, as: 'approve'
        get 'reject/:approval_id', action: :reject, as: 'reject'
      end
      collection do
        get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
        get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
        get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
        get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
        get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
        get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'
        get  'get_customs_clearance_cost/:customs_clearance', action: :get_customs_clearance_cost, as: 'get_customs_clearance_cost'
        get  'get_destination_ports/:origin_port', action: :get_destination_ports, as: 'get_destination_ports'
        get :tariffs
        patch :update
      end
    end
    resources :maritime_quotes do
      resources :quote_comments
    end
    resources :maritime_fcl_quotes do
      collection do
        get 'search_freight_types/:service_mode', action: :search_freight_types, as: 'search_freight_types'
        get 'set_freight_type/:freight_type', action: :set_freight_type, as: 'set_freight_type'
        get 'search_service_type_by_incoterm/:incoterm_id/:operation_type', action: :search_service_type_by_incoterm, as: 'search_service_type_by_incoterm'
        get 'search_service_type_by_operation_type/:operation_type/:incoterm_id', action: :search_service_type_by_operation_type, as: 'search_service_type_by_operation_type'
        get 'get_port_coordinates/:port_id', action: :get_port_coordinates, as: 'get_port_coordinates'
        get 'get_optional_service/:optional_service_id', action: :get_optional_service, as: 'get_optional_service'

        get :tariffs
      end
    end
    resources :maritime_lcl_quotes
    resources :reports
    resources :maritime_shipments
    resources :profile, only: %i[edit update]
    root 'dashboard#dashboard'
  end

  resources :user_steps
  match "user_steps/client", to: "user_steps#client", via: "post"

  namespace :admin do
    get 'dashboard/changelog'

    resources :changelogs do
      resources :comments
    end
    resources :tariff_rates
    resources :maritime_shipments do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :bookings
    resources :customs
    resources :teams
    resources :logs do
      member do
        get 'restore'
      end
    end
    resources :charges
    resources :maritime_lcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :maritime_fcl_rates do
      collection do
        get 'download_sample'
        post 'import'
      end
    end
    resources :profile, only: %i[edit update]
    resources :clients do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end
      member do
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'

        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact

        get :new_sender
        get :edit_sender
        get :show_sender
        delete :destroy_sender
        post :add_sender
        post :update_sender

        get :new_client_product
        get :edit_client_product
        get :show_client_product
        delete :destroy_client_product
        post :add_client_product
        post :update_client_product

        get :new_client_document
        get :edit_client_document
        get :show_client_document
        get :download_client_document
        delete :destroy_client_document
        post :add_client_document
        patch :update_client_document
        put :update_client_document

        get :import_csv_file
      end
    end
    resources :suppliers do
      collection do
        get 'filter_states/:country_id', action: :filter_states, as: 'filter_states'
      end

      member do
        get :new_address
        get :edit_address
        get :show_address
        delete :destroy_address
        post :add_address
        post :update_address

        get :new_phone
        get :edit_phone
        get :show_phone
        delete :destroy_phone
        post :add_phone
        post :update_phone

        get :new_contact
        get :edit_contact
        get :show_contact
        delete :destroy_contact
        post :add_contact
        post :update_contact
        # get :update_readonly
        get 'update_readonly/:readonly', action: :update_readonly, as: 'update_readonly'
      end
    end
    resources :membership_plans
    resources :services
    resources :criteria
    resources :packaging_types
    resources :taxes
    resources :documents
    resources :ports
    resources :products
    resources :access_roles do
      collection do
        get 'add_access/:role_id/:access_id/:system_module_id', action: :add_access, as: 'add_permission'
        get 'remove_access/:role_id/:access_id/:system_module_id', action: :remove_access, as: 'remove_permission'
      end
    end
    resources :roles do
      member do
        get :assign
      end
    end
    resources :users
    resources :containers
    resources :shipments
    resources :quotes do
      member do
        get :authorize
        post :declined
        delete :destroy
      end
    end

    resources :incidents, only: [:create]

    resources :maritime_quotes do
      resources :quote_comments
    end

    get 'icons/icons_fontawesome_brand'
    get 'icons/icons_fontawesome_duotone'
    get 'icons/icons_fontawesome_light'
    get 'icons/icons_fontawesome_regular'
    get 'icons/icons_fontawesome_solid'
    get 'icons/icons_nextgen_base'
    get 'icons/icons_nextgen_general'
    get 'icons/icons_stack_generate'
    get 'icons/icons_stack_showcase'
    get 'icons/icons_webfonts_faq'

    get 'ui/ui_accordion'
    get 'ui/ui_alerts'
    get 'ui/ui_badges'
    get 'ui/ui_breadcrumbs'
    get 'ui/ui_button_group'
    get 'ui/ui_buttons'
    get 'ui/ui_cards'
    get 'ui/ui_carousel'
    get 'ui/ui_collapse'
    get 'ui/ui_dropdowns'
    get 'ui/ui_list_filter'
    get 'ui/ui_modal'
    get 'ui/ui_navbars'
    get 'ui/ui_pagination'
    get 'ui/ui_panels'
    get 'ui/ui_popovers'
    get 'ui/ui_progress_bars'
    get 'ui/ui_scrollspy'
    get 'ui/ui_side_panel'
    get 'ui/ui_spinners'
    get 'ui/ui_tabs_accordions'
    get 'ui/ui_tabs_pills'
    get 'ui/ui_toasts'
    get 'ui/ui_tooltips'
    get 'ui/ui_tooltips_popovers'

    get 'intel/intel_analytics_dashboard'
    get 'intel/intel_introduction'
    get 'intel/intel_marketing_dashboard'
    get 'intel/intel_privacy'

    get 'settings/settings_how_it_works'
    get 'settings/settings_layout_options'
    get 'settings/settings_saving_db'
    get 'settings/settings_skin_options'

    get 'utilities/utilities_borders'
    get 'utilities/utilities_clearfix'
    get 'utilities/utilities_color_pallet'
    get 'utilities/utilities_display_property'
    get 'utilities/utilities_flexbox'
    get 'utilities/utilities_fonts'
    get 'utilities/utilities_helpers'
    get 'utilities/utilities_position'
    get 'utilities/utilities_responsive_grid'
    get 'utilities/utilities_sizing'
    get 'utilities/utilities_spacing'
    get 'utilities/utilities_typography'

    get 'tables/tables_basic'
    get 'tables/tables_generate_style'

    get 'datatables/datatables_alteditor'
    get 'datatables/datatables_autofill'
    get 'datatables/datatables_basic'
    get 'datatables/datatables_buttons'
    get 'datatables/datatables_colreorder'
    get 'datatables/datatables_columnfilter'
    get 'datatables/datatables_export'
    get 'datatables/datatables_fixedcolumns'
    get 'datatables/datatables_fixedheader'
    get 'datatables/datatables_keytable'
    get 'datatables/datatables_responsive'
    get 'datatables/datatables_responsive_alt'
    get 'datatables/datatables_rowgroup'
    get 'datatables/datatables_rowreorder'
    get 'datatables/datatables_scroller'
    get 'datatables/datatables_select'

    get 'statistics/statistics_c3'
    get 'statistics/statistics_chartist'
    get 'statistics/statistics_chartjs'
    get 'statistics/statistics_dygraph'
    get 'statistics/statistics_easypiechart'
    get 'statistics/statistics_flot'
    get 'statistics/statistics_peity'
    get 'statistics/statistics_sparkline'

    get 'plugins/plugins_appcore'
    get 'plugins/plugins_bootbox'
    get 'plugins/plugins_faq'
    get 'plugins/plugins_i18next'
    get 'plugins/plugins_navigation'
    get 'plugins/plugins_pacejs'
    get 'plugins/plugins_slimscroll'

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                                     :bigint           not null, primary key
#  advanced_parameters                    :boolean
#  annual_international_freight_shipments :bigint
#  authorized_credit                      :boolean          default(FALSE)
#  credit_limit                           :decimal(10, 4)   default(0.0)
#  deleted_at                             :datetime
#  has_credit                             :boolean          default(FALSE)
#  inactive                               :boolean          default(FALSE)
#  name                                   :string
#  rfc                                    :string
#  slug                                   :string
#  status                                 :bigint           default("pending")
#  website                                :string
#  created_at                             :datetime         not null
#  updated_at                             :datetime         not null
#  cfdi_id                                :bigint
#  currency_id                            :bigint
#  middleman_id                           :bigint
#  parent_entity_id                       :bigint
#  payment_method_id                      :bigint
#  payment_term_id                        :bigint
#  team_id                                :bigint
#  way_pay_id                             :bigint
#
# Indexes
#
#  index_clients_on_cfdi_id            (cfdi_id)
#  index_clients_on_currency_id        (currency_id)
#  index_clients_on_deleted_at         (deleted_at)
#  index_clients_on_middleman_id       (middleman_id)
#  index_clients_on_parent_entity_id   (parent_entity_id)
#  index_clients_on_payment_method_id  (payment_method_id)
#  index_clients_on_payment_term_id    (payment_term_id)
#  index_clients_on_slug               (slug) UNIQUE
#  index_clients_on_team_id            (team_id)
#  index_clients_on_way_pay_id         (way_pay_id)
#
# Foreign Keys
#
#  fk_rails_...  (cfdi_id => cfdis.id)
#  fk_rails_...  (currency_id => currencies.id)
#  fk_rails_...  (middleman_id => middlemen.id)
#  fk_rails_...  (parent_entity_id => clients.id)
#  fk_rails_...  (payment_method_id => payment_methods.id)
#  fk_rails_...  (payment_term_id => payment_terms.id)
#  fk_rails_...  (team_id => teams.id)
#  fk_rails_...  (way_pay_id => way_pays.id)
#
class Client < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  include Filterable

  before_save :set_team

  belongs_to :cfdi, inverse_of: :clients, optional: true
  belongs_to :currency, inverse_of: :clients, optional: true
  belongs_to :middleman, inverse_of: :clients, optional: true
  belongs_to :payment_method, inverse_of: :clients, optional: true
  belongs_to :payment_term, inverse_of: :clients, optional: true
  belongs_to :parent_entity, class_name: 'Client', inverse_of: :parent_entity, optional: true
  belongs_to :way_pay, inverse_of: :clients, optional: true
  belongs_to :team, inverse_of: :clients, optional: true

  has_one :bank_account, inverse_of: :client, dependent: :destroy
  has_one_attached :contract
  has_one_attached :logo

  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :client_documents, inverse_of: :client, dependent: :destroy
  has_many :client_products, inverse_of: :client, dependent: :destroy
  has_many :contacts, as: :contactable, dependent: :destroy
  has_many :phones, as: :phoneable, dependent: :destroy
  has_many :documents, through: :client_documents, inverse_of: :clients
  has_many :products, through: :client_products, inverse_of: :clients
  has_many :senders, as: :senderable, dependent: :destroy
  has_many :maritime_quotes, dependent: :destroy, inverse_of: :client
  has_many :maritime_shipments, dependent: :destroy, inverse_of: :client

  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :contacts, allow_destroy: true

  validates :name, presence: true

  enum status: { pending: 0, authorized: 1, denied: 2 }
  enum annual_international_freight_shipments: { '500': 0, '100': 1, '25': 2, none_first: 3, none_ship: 4 }

  def self.columns_names(columns_included)
    columns = column_names
    columns_excluded = columns - columns_included
    columns - columns_excluded
  end

  def self.all_columns_names
    columns_excluded = %w[id parent_entity_id advanced_parameters slug created_at updated_at
                          deleted_at currency_id cfdi_id way_pay_id team_id payment_term_id
                          payment_method_id middleman_id inactive]
    columns = column_names
    columns - columns_excluded
  end

  def principal_contact
    principal_contact = Contact.new
    contacts.each do |contact|
      principal_contact = contact if contact.principal == true
    end
    principal_contact
  end

  private

  def set_team
    team_default = Team.first
    if team_default.nil?
      employee = Employee.first
      new_team = Team.create!(name: 'Default')
      TeamMember.create!(team: new_team, employee: employee)
      self.team = new_team
    else
      self.team = team_default
    end
  end
end

app/models/sender.rb
# == Schema Information
#
# Table name: senders
#
#  id              :bigint           not null, primary key
#  address         :string
#  contact         :string
#  deleted_at      :datetime
#  email           :string
#  name            :string
#  phone           :string
#  rfc             :string
#  senderable_type :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  senderable_id   :bigint
#
# Indexes
#
#  index_senders_on_deleted_at  (deleted_at)
#  index_senders_on_senderable  (senderable_type,senderable_id)
#
class Sender < ApplicationRecord
  audited

  has_one_attached :logo

  belongs_to :senderable, polymorphic: true

  has_many :sender_sender_types, inverse_of: :sender, dependent: :destroy
  has_many :sender_types, through: :sender_sender_types, inverse_of: :senders

  has_many :phones, as: :phoneable, dependent: :destroy

  validates :name, presence: true

  def principal_phone?
    principal_phone = false
    phones.each do |phone|
      principal_phone = true if phone.principal == true
    end
    principal_phone
  end

  # function that obtains the data from the contact's main telephone number
  def principal_phone
    principal_phone = Phone.new
    phones.each do |phone|
      principal_phone = phone if phone.principal == true
    end
    principal_phone
  end

  # function that gets the main phone number of the principal contact.
  def phone
    principal_phone.number.blank? ? '' : principal_phone.number.to_s.strip
  end

  # function that obtains the number with extension of the main telephone of the principal contact.
  def phone_with_extension
    extension + phone
  end

  def extension
    principal_phone.extension.presence || ''
  end

  # function that obtains the country code number of the main telephone of the principal contact.
  def phone_with_country_code
    country_code + phone
  end

  def country_code
    principal_phone.code.blank? ? '' : "#{principal_phone.code} "
  end
end

app/models/sender_type.rb
# == Schema Information
#
# Table name: sender_types
#
#  id         :bigint           not null, primary key
#  deleted_at :datetime
#  inactive   :boolean          default(FALSE)
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_sender_types_on_deleted_at  (deleted_at)
#
class SenderType < ApplicationRecord
  audited

  has_many :sender_sender_types, inverse_of: :sender_type
  has_many :senders, through: :sender_sender_types, inverse_of: :sender_types
end

app/views/admin/clients/senders/_collection.html.erb
<% unless @senders.blank?
  @senders.each_slice(3) do |group| %>
    <div class="row mb-2">
      <% group.each do |sender| %>
        <div class="col-md-4">
          <%= render 'admin/clients/senders/sender', sender: sender %>
        </div>
      <% end %>
    </div>
 <% end %>
<% else %>
  <div class="not-register">
    <%= "#{t('views.shared.text.not_records')} de #{t('activerecord.models.sender.other')}." %>
  </div>
<% end %>

app/views/admin/clients/senders/_edit_sender_form.html.erb
<%= simple_form_for @sender, url: url_for(controller: 'admin/clients', action: 'update_sender'), html: {id: 'form_sender'}, remote: true do |f|%>
  <%= render 'admin/clients/senders/form' , f: f%>
<%  end %>

app/views/admin/clients/senders/_form.html.erb
<%= f.hidden_field :senderable_type, value: 'Client' %>
<%= f.hidden_field :senderable_id, value: @client.id%>
<%= hidden_field_tag :sender_id, @sender.id %>
<%= hidden_field_tag :is_sender, true %>
<%= hidden_field_tag :id %>

<div class="form-group row">
  <div class="col-md-6">
    <%=f.input :name, placeholder: t('activerecord.attributes.sender.name'), input_html: { title: t('views.admin.suppliers.instructions.first_name'), data: { toggle: "tooltip", placement: "top" } } %>
  </div>
  <div class="col-md-6">
    <%=f.input :rfc, placeholder: t('activerecord.attributes.sender.rfc') %>
  </div>
</div>
<div class="form-group row">
  <div class="col-md-6">
    <%=f.input :email, placeholder: t('activerecord.attributes.sender.email') %>
  </div>
  <div class="col-md-6">
    <%= f.input :contact, maxlength: 50, input_html: { class: 'form-control-sm'},placeholder: t('activerecord.attributes.sender.contact')%>
  </div>
</div>

<div class="form-group row">
  <div class=" col-md-4 col-sm-12 mt-2">
    <%= f.label :sender_type_ids, t("activerecord.attributes.sender.sender_type_ids") %>
    <%= f.select :sender_type_ids, options_for_select(SenderType.all.collect { |st| [st.name, st.id] }, @sender.sender_type_ids), {}, { class: 'form-control', multiple: 'multiple' }%>
  </div>
</div>

app/views/admin/clients/senders/_new_sender_form.html.erb
<%= simple_form_for @sender, url: url_for(controller: 'admin/clients', action: 'add_sender'), remote: true do |f|%>
  <%= render 'admin/clients/senders/form' , f: f%>
<%  end %>

app/views/admin/clients/senders/_sender.html.erb
<div id="c_1" class="card border shadow-0 mb-g shadow-sm-hover" data-filter-tags=<%= sender.name.truncate(15) %>>
  <div class="card-body border-faded border-top-0 border-left-0 border-right-0 rounded-top">
    <div class="d-flex flex-row align-items-center">
      <span class="mr-3">
        <i class="fas fa-truck-loading"></i>
      </span>
      <div class="info-card-text flex-1">
        <a href="javascript:void(0);" class="fs-xl text-truncate text-truncate-lg text-info" data-toggle="dropdown" aria-expanded="false">
          <%= sender.name.truncate(15) %>
          <i class="<%= Rails.configuration.icon_prefix %> fa-angle-down d-inline-block ml-1 fs-md"></i>
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" onclick="showSenderButton(<%= sender.id %>)"> <%= t('views.shared.buttons.show') %></a>
          <a class="dropdown-item" onclick="editSenderButton(<%= sender.id %>)"> <%= t('views.shared.buttons.edit') %></a>
          <a class="dropdown-item" onclick="deleteSenderButton(<%= sender.id %>)"><%= t('views.shared.buttons.delete') %></a>

        </div>
      </div>
      <button class="js-expand-btn btn btn-sm btn-default d-none" data-toggle="collapse" data-target="#c_1 > .card-body + .card-body" aria-expanded="false">
        <span class="collapsed-hidden">+</span>
        <span class="collapsed-reveal">-</span>
      </button>
    </div>
  </div>
  <div class="card-body p-0 collapse show">
    <div class="p-3">
      <span class="fs-sm fw-400 mt-4 text-muted">
        <i class="fal fa-mailbox mr-2"></i> <%= sender.email.truncate(15) %> </span>
      <span class="fs-sm fw-400 mt-4 text-muted">
        <i class="fal fa-id-card mr-2"></i> <%= sender.rfc %> </span>
      <span class="fs-sm fw-400 mt-4 text-muted">
        <i class="fal fa-flag mr-2"></i><%=
        if sender.extension != ""
          sender.phone_with_extension
        elsif sender.country_code != ""
          sender.phone_with_country_code
        end %>
      </span>
    </div>
  </div>
</div>

<% content_for :scripts_block do %>
  <script>
      function editSenderButton(sender_id) {
          $.ajax({
              method: "GET",
              url: "/admin/clients/" + $("#client_id").val() + "/edit_sender",
              data: {sender_id: sender_id},
              success: function (data) {
                  console.log(data);
              },
              error: function (data) {
              }
          });
      }

      function deleteSenderButton(sender_id) {
          var confirmation = confirm("¿Esta seguro de eliminar el remitente?");
          if (confirmation) {
              $.ajax({
                  method: "DELETE",
                  url: "/admin/clients/" + $("#client_id").val() + "/destroy_sender",
                  data: {sender_id: sender_id},
                  success: function (result) {
                      console.log("si se elimino");
                      $('#v-pills-senders-information-tab').trigger("click");
                      console.log(result);
                  },
                  error: function (data) {
                  }
              });
          }
      }

      function showSenderButton(sender_id){
          $.ajax({
              method: "GET",
              url: "/admin/clients/" + $("#client_id").val() + "/show_sender",
              data: {sender_id: sender_id},
              success: function (result) {

              },
              error: function (data) {
              }
          });
      }
  </script>
<% end %>

app/views/admin/clients/senders/_show.html.erb
<div class="row">
  <div class="col-xl-6">
    <div class="row">
      <label class="col-xl-3 col-lg-3 col-form-label text-right">
        <b><%= "#{t('activerecord.attributes.sender.name')}:" %>
        </b></label><label class="col-xl-9 col-lg-9 col-form-label"><%= @sender.name %>
    </label></div>
    <div class="row">
      <label class="col-xl-3 col-lg-3 col-form-label text-right">
        <b><%= "#{t('activerecord.attributes.sender.rfc')}:" %>
        </b></label><label class="col-xl-9 col-lg-9 col-form-label"><%= @sender.rfc %>
    </label></div>
    <div class="row">
      <label class="col-xl-3 col-lg-3 col-form-label text-right">
        <b><%= "#{t('activerecord.attributes.sender.email')}:" %>
        </b></label><label class="col-xl-9 col-lg-9 col-form-label"><%= @sender.email %>
    </label></div>
  </div>
  <div class="col-xl-6">
    <div class="row">
      <label class="col-xl-3 col-lg-3 col-form-label text-right">
        <b><%= "#{t('activerecord.attributes.sender.contact')}:" %>
        </b></label><label class="col-xl-9 col-lg-9 col-form-label"><%= @sender.contact %>
    </label></div>
  </div>
</div>